spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    generate-ddl: true
    show-sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
