spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/projectdb
    username: postgres
    password: postgres
  jpa:
    generate-ddl: true
    show-sql: true
eureka:
  client:
    defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
