server:
  port: 8585
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/projectdb
    username: postgres
    password: postgres

  jpa:
    generate-ddl: —Åreate 
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka
  instance:
    prefer-ip-address: true
